### ISSUE TITLE
Refusing to serve hidden file, via 404 Error

### ISSUE THREAD

**Issue by ChristofKaufmann** [jupyterlab-contrib/jupyter-archive#115]
## Description

I am running a JupyterHub on a Kubernetes Cluster. I use two different images, a [tensorflow-gpu](https://gitlab.cvh-server.de/ckaufmann/gpu-cluster-images/-/blob/master/tensorflow-gpu-with-vscode/Dockerfile) and a [tensorflow-cpu](https://gitlab.cvh-server.de/ckaufmann/gpu-cluster-images/-/blob/master/tensorflow-cpu-with-vscode/Dockerfile) image. In the GPU image the download works fine, but in the CPU image it does not work. When I click "Download as an archive", all I get is an empty browser tab.

## Reproduce

1. `docker run --name tf-cpu -d -it -p 8888:8888 -e GRANT_SUDO=yes -e JUPYTER_ENABLE_LAB=yes --user root christofkaufmann/tensorflow-cpu-notebook:fa57d1fa && sleep 2 && docker logs tf-cpu && docker exec -it tf-cpu bash`
2. Click on the printed link http://127.0.0.1:8888/lab?token=...
3. Right-click on the folder "work" and select "Download as an archive".
4. Nothing happens, beside opening a new browser tab.

## Expected behavior

An archive should be created and downloaded, like with the GPU image (christofkaufmann/tensorflow-gpu-notebook:fa57d1fa). In the GPU image the packages are older. If you need the versions, let me know.

## Context

This refers to the CPU image where the bug is triggered.

- Python package version: 3.3.0 from conda-forge
- Extension version:
  ```output
  JupyterLab v3.5.2
  /opt/conda/share/jupyter/labextensions
          jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
          jupyterlab-execute-time v2.3.1 enabled OK (python, jupyterlab_execute_time)
          jupyterlab-system-monitor v0.8.0 enabled OK (python, jupyterlab-system-monitor)
          jupyterlab-topbar-extension v0.6.1 enabled OK (python, jupyterlab-topbar)
          jupyter-matplotlib v0.11.2 enabled OK
          @hadim/jupyter-archive v3.3.0 enabled OK (python, jupyter-archive)
          @jupyterlab/server-proxy v3.2.2 enabled OK
          @jupyter-server/resource-usage v0.7.1 enabled OK (python, jupyter-resource-usage)
          @jupyter-widgets/jupyterlab-manager v5.0.5 enabled OK (python, jupyterlab_widgets)
  ```
  ```output
  Config dir: /home/jovyan/.jupyter
  
  Config dir: /opt/conda/etc/jupyter
      jupyter_archive enabled
      - Validating jupyter_archive...
        jupyter_archive 3.3.0 OK
      jupyter_server_proxy enabled
      - Validating jupyter_server_proxy...
        jupyter_server_proxy  OK
      jupyter_resource_usage enabled
      - Validating jupyter_resource_usage...
        jupyter_resource_usage 0.7.1 OK
      jupyter_server_terminals enabled
      - Validating jupyter_server_terminals...
        jupyter_server_terminals 0.4.3 OK
      jupyterlab enabled
      - Validating jupyterlab...
        jupyterlab 3.5.2 OK
      nbclassic enabled
      - Validating nbclassic...
        nbclassic 0.4.8 OK
      nbgitpuller enabled
      - Validating nbgitpuller...
        nbgitpuller 1.1.1 OK
      notebook_shim enabled
      - Validating notebook_shim...
        notebook_shim  OK
  
  Config dir: /usr/local/etc/jupyter
  ```
- Server is running Debian 11, but it should not matter, because it runs inside a container.
- Firefox 110.0.1, Chrome 110.0.5481.177

<details><summary>Command Line Output</summary>
This is the relevant part of the log output from the `jupyter-USER` pod.
<pre>
/opt/conda/lib/python3.10/site-packages/jupyter_archive/handlers.py:123: RuntimeWarning: coroutine 'AsyncFileContentsManager.is_hidden' was never awaited
  if cm.is_hidden(archive_path) and not cm.allow_hidden:
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
[I 2023-03-15 17:16:17.137 SingleUserLabApp handlers:124] Refusing to serve hidden file, via 404 Error
</pre>
</details>

<details><summary>Web Browser Output</summary>
An empty tab is opened, as described in #99.
</details>

So, I think the important bit is the message `/opt/conda/lib/python3.10/site-packages/jupyter_archive/handlers.py:123: RuntimeWarning: coroutine 'AsyncFileContentsManager.is_hidden' was never awaited`

**Comment by fcollonval** [comment]
Thanks for reporting @ChristofKaufmann 

You need to update this extension - that bug was fixed in [v3.3.3](https://github.com/jupyterlab-contrib/jupyter-archive/releases/tag/v3.3.3)

**Comment by ChristofKaufmann** [comment]
Hmm, strange. [conda-forge](https://anaconda.org/conda-forge/jupyter-archive) shows that the current version is 3.3.4 and I tried it yesterday. So I get 3.3.0 probably because of `--no-update-deps` in the `mamba install` command, which I added to keep the docker layers small. I will try without and report back.

**Comment by ChristofKaufmann** [comment]
Updating `jupyter-archive` from 3.3.0 to 3.3.3 or 3.3.4 requires to downgrade `jupyter_server` from 2.0.6 to 1.23.6. Is there an incompatibility with version 2 or might this be a wrong dependency in the feedstock?

**Comment by fcollonval** [comment]
This is mistake when publishing the new package on conda-forge as 3.3.4 relaxed the constrain on `jupyter-server`. Let me release a new version on conda-forge.

> In case you need the new authentication/authorization feat. of Jupyter Server v2, it is backward compatible with Jupyter Server v1.

**Comment by ChristofKaufmann** [comment]
OK, I saw you added that requirement in https://github.com/conda-forge/jupyter-archive-feedstock/commit/6ee412e45573e406f94973d693ee107d4f0ecdbd using PR https://github.com/conda-forge/jupyter-archive-feedstock/pull/22. I just wanted to ask about the background of it.

**Comment by ChristofKaufmann** [comment]
OK, good to know. The dependency change should resolve the issue. Thank you very much! This was very fast.
