### ISSUE TITLE
UI for the notebook "old" client

### ISSUE THREAD

**Issue by hadim** [jupyterlab-contrib/jupyter-archive#21]
As suggested here: https://discourse.jupyter.org/t/jupyter-archive-make-download-and-extract-archive-files/2363/13?u=hadim

**Comment by hadim** [comment]
I don't really have the time neither the need for this feature so I don't think I'll work on it in the near future. That being said I will be happy to review a PR.

**Comment by fcollonval** [comment]
As the classical notebook is retiring from active development, I let this issue open only if somebody is interested in implementing the feature.

Here are two repositories that could provide a code basis for this feature:
- https://github.com/data-8/nbzip
- https://github.com/ryanlovett/jupyter-tree-download

**Comment by fcollonval** [comment]
I'm closing this one as the classical notebook is retiring. For those interested by using this extension with a UI close to the classical notebook, I suggest using [JupyterLab in simple mode](https://jupyterlab.readthedocs.io/en/stable/user/interface.html#tabs-and-simple-interface-mode).
