### ISSUE TITLE
Question about packaging

### ISSUE THREAD

**Issue by hadim** [jupyterlab-contrib/jupyter-archive#28]
@fcollonval There is something I am not sure about: why do I keep pushing new versions to npm (https://www.npmjs.com/package/@hadim/jupyter-archive) if the lab extension is already embedded to both the `pip` and `conda` packages. 

The only advantage I see is that people can discover it through JLab extension manager but they would still need to install the server extension anyway...

What do you think?

**Comment by fcollonval** [comment]
Yes, the good way of packaging extensions is not really solved unfortunately. The two following arguments come to my mind for why a npm package should be published:
- Ensuring that nobody else publish another extension with the same name - albeit this does not require keeping the package up-to-date
- Allow the frontend extension to be used for installation with non-default `JUPYTERLAB_DIR`

The latter is actually used in my company to provide a customized jupyterlab without interfering with the original one taking advantage of that [approach](https://github.com/jonmmease/jupyterlab_delux).

**Comment by hadim** [comment]
Ok, thanks for the comments.

I'll keep publishing NPM packages then.

I let this issue open for some time in case a Jupyter dev wants to comment.

**Comment by fcollonval** [comment]
The status with JupyterLab 3 has been clarified. But this is still advised to publish on npm in case somebody would be interested in using the frontend source code (unlikely though).

**Comment by fcollonval** [comment]
Now that the extension is ported on JupyterLab 3. This is clarified, for final user only the python package is required.
