### ISSUE TITLE
No unzip option to unzip a file inside jupyter lab.

### ISSUE THREAD

**Issue by AvisekNaug** [jupyterlab-contrib/jupyter-archive#39]
I have installed jupyter-archive via conda.

`conda install -c conda-forge jupyter-archive`

I expected that this will show a unzip option but it doesn't

I have enabled 3rd party extensions too.

Clicking "open with" provides the "Editor" option but that does not unzip the file

Instead this happens

![Issue](https://i.imgur.com/KbEH4aD.png)

I expected to see a unzip/extract option

**Comment by hadim** [comment]
See https://github.com/hadim/jupyter-archive/issues/40

**Comment by fcollonval** [comment]
Did you rebuild jupyterlab after the installation?

If not, you need to do the following to install this extension with conda:

```bash
conda install -c conda-forge nodejs jupyter-archive
jupyter lab build
```

**Comment by fcollonval** [comment]
Closing this one as it is no more relevant for JupyterLab 3
