### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by hadim** [jupyterlab-contrib/jupyter-archive#40]
I am not really using neither working on that extension anymore. Integration to jupyter failed (see https://github.com/jupyter-server/jupyter_server/pull/252).

That being said I think this extension is used by a small (or probably a tiny) community. Would someone like to have admin access in order to keep maintaining the project?

ping @fcollonval here

**Comment by fcollonval** [comment]
@hadim Thanks for pinging me. I gladly take over the maintenance if you would like. If you agree, could you grant me the rights on the pypi and npm packages too please?

**Comment by hadim** [comment]
Thanks for doing that!

You should have received invitation for gh, pypi and npm.

I'll let you close here once you're all setup.

**Comment by fcollonval** [comment]
@hadim I successfully publish a new version on pypi and npm - thanks for the rights. I only have a request, I don't have full rights on the github repository. Could you please increase my rights? In particular I'm unable to access the project settings.

**Comment by hadim** [comment]
I can't grant you more permissions from the settings of the repo. What do you want to modify? I am fine doing it.

**Comment by fcollonval** [comment]
> What do you want to modify?

I read the rules of GitHub and this is not possible on personal projects. But luckily I just started a jupyterlab-contrib organization to hope gathering projects in the same situation than this one.

You should have received an invitation to join the `jupyterlab-contrib` organization. Could you accept it and then transfer the project to that organization.

> Only on organization can the rights micro-manage.

**Comment by hadim** [comment]
Done!

**Comment by fcollonval** [comment]
Great everything is set now.
