### ISSUE TITLE
[JupyterHub] 404 error on Download as archive

### ISSUE THREAD

**Issue by BobCashStory** [jupyterlab-contrib/jupyter-archive#47]
When i run jupyterlab in local it works but not behind jupyterhub.

it try to open this URL :
`https://app.dev.naas.ai/user/bob@cashstory.com/directories/test_email?archiveToken=***&archiveFormat=zip&followSymlinks=true&downloadHidden=false&_xsrf=***`

**Comment by NewbieOfUESTC** [comment]
Maybe you should restart jupyterlab manually. I meet same error before I restart it.

**Comment by fcollonval** [comment]
@BobCashStory which browser are you using?

**Comment by potoo0** [comment]
restart your lab:
**File** -> *Hub Control Panel* -> *Stop My Server* -> *Start My Server*, enjoy.
