### ISSUE TITLE
Memory leak when archive large files and network is slow at the same time

### ISSUE THREAD

**Issue by eastonsuo** [jupyterlab-contrib/jupyter-archive#59]
## Description
* memory go up when archiving big file

## Reproduce

1. when archive and download a big floder using jupyter_archive
2. and the network is slower than the speed of archive
3. the memory will go up and there is no limit !!!

## solution
* I think it is because the is no limit on the buffer
* both `_write_buffer` of RequstHandler, as well as `_write_buffer` of IOStream, which is base of tornado framework, should be limited
* limit the buffer can solve this issue, and I will do a pull request

**Comment by fcollonval** [comment]
Closed by #62
