### ISSUE TITLE
Allow to contain `.` in extraction file name

### ISSUE THREAD

**Issue by aidy1991** [jupyterlab-contrib/jupyter-archive#63]
## Is your feature request related to a problem? Please describe.

I have a suggestion for improvement regarding the extract function of jupyter_archive.
Currently, extract fails if the target file name contains `. ` in the target filename.
I think this is because the file extension retrieved by `suffixes()` is compared with the white list.
To allow file names to contain `. ` in the filename, jupyter-archive will be more useful, I think.

## Describe the solution you'd like

How about checking the extension white list for backward matching?
For example, if we have a file named `hoge.old.tar.gz`, it will backward match `tar.gz`, so we can run extraction.

## Additional context

- Python package version:

- Extension version:

- Operating System and its version:

**Comment by fcollonval** [comment]
Thanks for the suggestion. Would you like to open a PR?

The code to blame is there:
https://github.com/jupyterlab-contrib/jupyter-archive/blob/ffa8a283063fecedf2ae8913edb985e781b78247/jupyter_archive/handlers.py#L65

**Comment by aidy1991** [comment]
Thank you for your quick response.
OK, I'll try to create PR!
