### ISSUE TITLE
Update 2.x version code?

### ISSUE THREAD

**Issue by Wh1isper** [jupyterlab-contrib/jupyter-archive#76]
## Describe the solution you'd like

I am using Jupyterlab2 with some custom front-end plugin
So I am using 2.x version jupyter-archive
But there are many bug fixes that have not been synced to version 2.x, like zip a dir named aaa.bbb, the zip file name is displayed as aaa.zip, and I found that this had been fixed in 3.x version
Do we have any updates planned for version 2.x? Maybe I can refer to the code for version 3.x to update version 2.x?

## Additional context

- Python package version:

- Extension version:

- Operating System and its version:

**Comment by fcollonval** [comment]
Feel free to open a PR that merges the master branch in 2.x. If it works, I could do a new release.

**Comment by Wh1isper** [comment]
> Feel free to open a PR that merges the master branch in 2.x. If it works, I could do a new release.

Okay, I will do this work when I have time

**Comment by Wh1isper** [comment]
> Feel free to open a PR that merges the master branch in 2.x. If it works, I could do a new release.

Not many code changes https://github.com/jupyterlab-contrib/jupyter-archive/pull/77
