### ISSUE TITLE
Broken archived file with slow network and large data

### ISSUE THREAD

**Issue by aidy1991** [jupyterlab-contrib/jupyter-archive#80]
## Description

I found a problem with data loss when I tried to archive download a large file in a slow network environment.
The download will complete successfully, but this file will fail to extract on local PC.

As a result of my investigation, I found that if the archive process completes when the `stream._write_buffer` exceeds the `DownloadArchiveHandler.stream_max_buffer_size`, the `DownloadArchiveHandler._ write_buffer` will be lost. This is because [`flush`](https://github.com/jupyterlab-contrib/jupyter-archive/blob/master/jupyter_archive/handlers.py#L169), which is called after the archive process finishes, is [skipped](https://github.com/jupyterlab-contrib/jupyter-archive/blob/master/jupyter_archive/handlers.py#L108).

In my application, I solved this by modifying `DownloadArchiveHandler.flush()` to add a `force` option, but this method is a bit clunky to use in common use cases.
~However, this method is a bit rough to use in general use cases, because the stream buffer will temporarily exceed the max size.~

I have also tried implementing a while loop to wait until the stream buffer becomes small enough, and confirmed that this solves the problem.

## Reproduce

I think this problem is a little difficult to reproduce. Even in my application, I was unable to reproduce it in a local environment, but was able to reproduce it by accessing it from a slow network environment.

In addition to the speed of the network, it also depends on the size of the file to be downloaded.

On my slow network environment, I had this problem when I tried to archive and download a 200MB file. If the network speed is a little faster than this, the problem does not occur until I download a larger file.

I tried the network throttle in the chrome dev tool, but it failed to limit the speed of the file download. Please let me know if there is a better way.

## Expected behavior

The download completes normally, and the file can be extracted.

## Context

- Python package version:

- Extension version:

- Operating System and its version: 
- Browser and its version: 

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Web Browser Output</summary>
<pre>
Paste the output from your browser web console here.
</pre>
</details>

If there is any other information you need, please let me know.

**Comment by fcollonval** [comment]
Thanks for reporting the bug.

Is that problem occurring in the latest version? It looks like #62 added the needed protection (loop to limit writing to the buffer and delaying flush), isn't it?

> I tried the network throttle in the chrome dev tool, but it failed to limit the speed of the file download. Please let me know if there is a better way.

No better way here.

**Comment by aidy1991** [comment]
> Is that problem occurring in the latest version? It looks like #62 added the needed protection (loop to limit writing to the buffer and delaying flush), isn't it?

I'm facing this problem in the latest version. Rather, I think #62 contains this bug.

I found a way to reproduce this.

1. throttle network speed by [@sitespeed.io/throttle](https://www.npmjs.com/package/@sitespeed.io/throttle) with below setting.
2. access jupyter lab via private ip address (Note: when accessing it via localhost, throttle cannot work well)
3. prepare 200mb file in a directory by below codes.
4. download as archive the directory

#### throttle setting example
```
$ throttle --up 4000 --down 4000
```

#### generate large file by python codes

```python
def generate_big_random_bin_file(filename,size):
    import os 
    with open('%s'%filename, 'wb') as fout:
        fout.write(os.urandom(int(size)))
generate_big_random_bin_file("./200mb_dir/200mb", 0.2 * 1024 * 1024 * 1024)
```

In my environment, this method reproduced the problem with high probability.

**Comment by fcollonval** [comment]
Thanks for sharing a detailed way to reproduce the problem. I don't have much time right know to test it. Would you be willing to push a fix?

**Comment by aidy1991** [comment]
OK, I'll make PR to fix this issue.

By the way, I found another bug when I was investigating this, so I will create another issue.
