### ISSUE TITLE
Throws 404 when trying to download

### ISSUE THREAD

**Issue by remyvanlis** [jupyterlab-contrib/jupyter-archive#83]
Hi there,

Got myself a clean install of Jupyterlab ready to go, working all fine. I need a way to download folders as an archive, so installed this extension. However, when I click "Download as an Archive", it just throws me a 404:

`404 GET /user/amuseic/directories/Notebooks/Nolen?archiveToken=sx3k30n763h6n5dy564c&archiveFormat=zip&followSymlinks=true&downloadHidden=false&_xsrf=2%7Cdf7fc5ba%7Cde6993628513bdb312f77d0`

I've changed the host, since I'm running this on a VM that I don't work on, so host is local ip using a reversed proxy with Nginx to a DNS service. Is that why it might not work, and how might I fix that?

Kind regards,
Remy

**Comment by fcollonval** [comment]
Hey @remyvanlis 

> I've changed the host, since I'm running this on a VM that I don't work on, so host is local ip using a reversed proxy with Nginx to a DNS service. Is that why it might not work, and how might I fix that?

I would say no

Could you in a terminal within JupyterLab execute the following commands:

```
jupyter server extension list
jupyter serverextension list
```

And report here the output please?

**Comment by fcollonval** [comment]
You likely have an error when installing the extension. If you compare with the result obtained on the Binder test for this extension:

![image](https://user-images.githubusercontent.com/8435071/153715465-1cbf7b77-d845-4aa4-8a8f-81768213a56c.png)

You should also see `jupyter_archive` when running those commands.

I adviced you to reinstall the extension with `pip install -U jupyter-archive` in your VM.

**Comment by remyvanlis** [comment]
You're entirely right. Simply installing it manually worked perfect (I installed it through the extensions tab in Jupyter before). Thanks, great package:)
