### ISSUE TITLE
Data corruption due to race condition

### ISSUE THREAD

**Issue by aidy1991** [jupyterlab-contrib/jupyter-archive#86]
## Description
In jupyter-archive, reading and writing of `_write_buffer` is performed in different threads. So, for example, if a write to `_write_buffer` is performed between L1066 and L1067 in `RequestHandler.flush()`, buffer data will be lost.

Ref: https://github.com/tornadoweb/tornado/blob/master/tornado/web.py#L1066-L1067

I found that using `threading.Lock()` to lock `write()` and `flush()` solved the problem.
I will send PR if necessary.

## Reproduce

It is very difficult to reproduce this intentionally. If you archive several GB files, it will happen more often, but not all the time. 
In my application, I was able to reproduce it with high frequency for certain data, but I think it depends on the environment of application.

## Expected behavior
Data can be extracted without corruption.

## Context

- Python package version:

- Extension version:

- Operating System and its version: 
- Browser and its version: 

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Web Browser Output</summary>
<pre>
Paste the output from your browser web console here.
</pre>
</details>

**Comment by fcollonval** [comment]
Thanks for reporting and providing a way to fix it (your solution sounds great). Would you mind opening a PR for this one too?

**Comment by aidy1991** [comment]
Sorry for the late reply. I will prepare a PR.
