### ISSUE TITLE
Download stops in 'New Tab'

### ISSUE THREAD

**Issue by forestbat** [jupyterlab-contrib/jupyter-archive#99]
When I try to download a directory as zip archive:
![图片](https://user-images.githubusercontent.com/23413915/196070176-19858268-7d4e-4a03-907e-73dba7a98b09.png)
("打包下载" means "Download as an archive)

The process will stop in a blank tab page, and I can't receive any file.

My version of jupyterlab is 3.4.4 and version of jupyter-archive is 3.3.1.

**Comment by JustSaX** [comment]
I have the same problem. I have the menu entries in Jupyterlab *Download Current Folder as an Archive* and *Download as an Archive* but when I click on one of the entries I only get an empty tab in Firefox or an empty download in Chrome. @forestbat how did you fix it?

Cheers
JustSax

**Comment by fcollonval** [comment]
@JustSaX could you open a new issue if you still have the error? Could you provide as much log information as possible?
